# Nombre del sitio
name: Include Poetry

# Título
title: Include Poetry

# Descripcón del sitio
description: Curso de preparación para las Olimpiadas de Informática, como la OMI y OMIPS

# Email
email: includepoetry@gmail.com

# Facebook
facebook:
  app_id: 201218926955149

# Autor
author: rivel_co

# Versión de Markdown
markdown: kramdown

# Google services
google_analytics: UA-74086952-1

# Base del sitio
# url: "https://include-poetry.github.io"
url: "https://www.include-poetry.com"
baseurl: /Code

# Excuidos de la conversión
exclude: [vendor, RecursosDev]

# Gemas - también en Gemfile
gems:
  - algoliasearch-jekyll
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Algolia - buscador
algolia:
  application_id: 'QO0HGR5828'
  index_name: 'MainIndexIPC'
  excluded_files:
    - index.html
    - 404.md
    - Motivacion/index.html
    - Topicos-adicionales/Karel/Tags/index.html
    - Topicos-adicionales/C++/Tags/index.html
    - Topicos-adicionales/C++/index.html
    - Topicos-adicionales/Karel/index.html
    - Problemas/Resueltos/C++/index.html
    - Problemas/Resueltos/C++/Tags/index.html
    - Buscador/index.html
  record_css_selector: 'p,ul,ol,blockquote,table'
  settings:
    attributesForFaceting:
      - tags
      - olimpiada
      - subject
      - author

# Variables del sitio
logo-grande-n: "/Multimedia/Logo/IPoetryN.png"
logo-chico-n: "/Multimedia/Logo/IPN.png"
logo-grande-b: "/Multimedia/Logo/IPoetryB.png"
logo-chico-b: "/Multimedia/Logo/IPB.png"
logo-pluma: "/Multimedia/Logo/RPlumaN.png"
iP-Sources: "https://www.include-poetry.com/IP-Sources"

# Colecciones 
collections:
  C: 
    output: true
    permalink: /C++/:path/
  Karel:
    output: true
    permalink: /Karel/:path/
  Otros-C:
    output: true
    permalink: /Otros-temas/C++/:title/
  Otros-Karel:
    output: true
    permalink: /Otros-temas/Karel/:title/
  Resueltos-C:
    output: true
    permalink: /Problemas/Resueltos/C++/:title/
  Descargables:
    output: false