# Nombre del sitio
name: Include Poetry

# Título
title: Include Poetry

# Descripcón del sitio
description: Curso de preparación para las Olimpiadas de Informática, como la OMI y OMIPS

# Email
email: includepoetry@gmail.com

# Facebook
facebook:
  app_id: 201218926955149

# Autor
author: rivel_co

# Versión de Markdown
markdown: kramdown

# Google services
google_analytics: UA-74086952-1

# Base del sitio url:  "http://localhost:4000"
url: "http://192.168.1.65:4000"
baseurl: /Code
host: 0.0.0.0

gems:
  - algoliasearch-jekyll
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

algolia:
  application_id: 'QO0HGR5828'
  index_name: 'IPCode'
  excluded_files:
    - index.html
    - 404.md
    - Motivacion/index.html
    - Topicos-adicionales/Karel/Tags/index.html
    - Topicos-adicionales/C++/Tags/index.html
  record_css_selector: 'p,ul,ol,blockquote,table'

# Excuidos de la conversión
exclude: [Montar.bat, IP-Code.sublime-workspace]

# Variables del sitio
logo-grande-n: "/Multimedia/Logo/IPoetryN.png"
logo-chico-n: "/Multimedia/Logo/IPN.png"
logo-grande-b: "/Multimedia/Logo/IPoetryB.png"
logo-chico-b: "/Multimedia/Logo/IPB.png"
logo-pluma: "/Multimedia/Logo/RPlumaN.png"
iP-Sources: "/Code/RecursosDev"

# Colecciones
collections:
  C: 
    output: true
    permalink: /C++/:path/
  Karel:
    output: true
    permalink: /Karel/:path/
  Topicos-C:
    output: true
    permalink: /Topicos-adicionales/C++/:categories/:title/
  Topicos-Karel:
    output: true
    permalink: /Topicos-adicionales/Karel/:categories/:title/
  Resueltos-C:
    output: true
    permalink: /Problemas/Resueltos/C++/:title/
  Descargables:
    output: false