# Nombre del sitio
name: Include Poetry

# Título
title: Include Poetry

# Descripcón del sitio
description: Curso de preparación para las Olimpiadas de Informática, como la OMI y OMIPS

# Email
email: includepoetry@gmail.com

# Facebook
facebook:
  app_id: 201218926955149

# Autor
author: rivel_co

# Versión de Markdown
markdown: kramdown

# Google services
google_analytics: UA-74086952-1

# Base del sitio
# url: "https://include-poetry.github.io"
url: "https://www.include-poetry.com"
baseurl: /Code

# Excuidos de la conversión
exclude: [vendor, RecursosDev]

# Gemas
gems:
  - algoliasearch-jekyll
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Algolia
algolia:
  application_id: 'QO0HGR5828'
  index_name:     'IPCode'
  read_only_api_key: 'eb04fe369bec3b6b078e4eb51ea48ae6'

# Variables del sitio
logo-grande-n: "/Multimedia/Logo/IPoetryN.png"
logo-chico-n: "/Multimedia/Logo/IPN.png"
logo-grande-b: "/Multimedia/Logo/IPoetryB.png"
logo-chico-b: "/Multimedia/Logo/IPB.png"
logo-pluma: "/Multimedia/Logo/RPlumaN.png"
iP-Sources: "https://www.include-poetry.com/IP-Sources"

# Colecciones 
collections:
  C: 
    output: true
    permalink: /C++/:path/
  Karel:
    output: true
    permalink: /Karel/:path/
  Topicos-C:
    output: true
    permalink: /Topicos-adicionales/C++/:categories/:title/
  Topicos-Karel:
    output: true
    permalink: /Topicos-adicionales/Karel/:categories/:title/
  Resueltos-C:
    output: true
    permalink: /Problemas/Resueltos/C++/:title/
  Descargables:
    output: false